{{- if .Values.redfishProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ceems-exporter.redfish-proxy.fullname" . }}-config
  namespace: {{ include "ceems-exporter.redfish-proxy.namespace" . }}
data:
  config.yaml: |
    redfish_config:
      tls_config:
        insecure_skip_verify: {{ .Values.redfishProxy.insecureSkipVerify }}
{{- end }}
