{{- if and .Values.redfishProxy.enabled (not (empty .Values.redfishProxy.webConfig)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ceems-exporter.redfish-proxy.fullname" . }}-web-config
  namespace: {{ include "ceems-exporter.redfish-proxy.namespace" . }}
stringData:
  config.yaml: |-
  {{- with .Values.redfishProxy.webConfig }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
