{{- if and .Values.admissionWebhooks.enabled .Values.admissionWebhooks.patch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "ceems-api-server.fullname" . }}-admission-create
  namespace: {{ template "ceems-api-server.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
{{- with .Values.admissionWebhooks.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "ceems-api-server.name" $ }}-admission-create
    {{- include "ceems-api-server.admission.webhook.labels" $ | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.admissionWebhooks.patch.ttlSecondsAfterFinished }}
  template:
    metadata:
      name:  {{ template "ceems-api-server.fullname" . }}-admission-create
{{- with .Values.admissionWebhooks.patch.podAnnotations }}
      annotations:
{{ toYaml .  | indent 8 }}
{{- end }}
      labels:
        app: {{ template "ceems-api-server.name" $ }}-admission-create
        {{- include "ceems-api-server.admission.webhook.labels" $ | nindent 8 }}
    spec:
      {{- if .Values.admissionWebhooks.patch.priorityClassName }}
      priorityClassName: {{ .Values.admissionWebhooks.patch.priorityClassName }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- include "ceems-api-server.imagePullSecrets" . | indent 8 }}
      {{- end }}
      containers:
        - name: create
          {{- $registry := .Values.global.imageRegistry | default .Values.admissionWebhooks.patch.image.registry -}}
          {{- if .Values.admissionWebhooks.patch.image.sha }}
          image: {{ $registry }}/{{ .Values.admissionWebhooks.patch.image.repository }}:{{ .Values.admissionWebhooks.patch.image.tag }}@sha256:{{ .Values.admissionWebhooks.patch.image.sha }}
          {{- else }}
          image: {{ $registry }}/{{ .Values.admissionWebhooks.patch.image.repository }}:{{ .Values.admissionWebhooks.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.admissionWebhooks.patch.image.pullPolicy }}
          args:
            - create
            - --host={{- include "ceems-api-server.admission.webhook.dnsNames" . | replace "\n" "," }}
            - --namespace={{ template "ceems-api-server.namespace" . }}
            - --secret-name={{ template "ceems-api-server.fullname" . }}-admission-controller-certs
            - --cert-name=tls.crt
            - --key-name=tls.key
          {{- with .Values.admissionWebhooks.createSecretJob }}
          securityContext:
          {{ toYaml .securityContext | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.admissionWebhooks.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "ceems-api-server.fullname" . }}-admission-webhook
      {{- with .Values.admissionWebhooks.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- if .Values.admissionWebhooks.patch.securityContext }}
      securityContext:
{{ toYaml .Values.admissionWebhooks.patch.securityContext | indent 8 }}
{{- end }}
{{- end }}
