{{- if and .Values.admissionWebhooks.enabled .Values.admissionWebhooks.patch.enabled .Values.admissionWebhooks.patch.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ template "ceems-api-server.fullname" . }}-admission-webhook
  namespace: {{ template "ceems-api-server.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-50"
  labels:
    app: {{ template "ceems-api-server.name" $ }}-admission-webhook
    {{- include "ceems-api-server.admission.webhook.labels" $ | nindent 4 }}
  {{- with .Values.admissionWebhooks.patch.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.admissionWebhooks.patch.serviceAccount.automountServiceAccountToken }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ include "ceems-api-server.imagePullSecrets" . | trim | indent 2 }}
{{- end }}
{{- end }}
