{{- if .Values.admissionWebhooks.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ceems-api-server.fullname" . }}-admission-controller-web-config
  namespace: {{ include "ceems-api-server.namespace" . }}
data:
  web-config.yaml: |+
    tls_server_config:
      cert_file: /certs/tls.crt
      key_file: /certs/tls.key
{{- end }}
