{{- if .Values.admissionWebhooks.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.admissionWebhooks.deployment.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "ceems-api-server.admission.controller.serviceAccountName" . }}
  namespace: {{ template "ceems-api-server.namespace" . }}
  labels:
    {{- include "ceems-api-server.admission.controller.labels" . | nindent 4 }}
  {{- with .Values.admissionWebhooks.deployment.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ include "ceems-api-server.imagePullSecrets" . | trim | nindent 2 }}
{{- end }}
{{- end }}
