{{- if and .Values.ceemsExporter.rbac.create .Values.ceemsExporter.enabled }}
{{- if or .Values.ceemsExporter.kubeRBACProxy.enabled .Values.ceemsExporter.collectors.k8s.enabled (gt (len .Values.ceemsExporter.rbac.extraClusterRoleRules) 0) (and .Values.redfishProxy.enabled .Values.redfishProxy.kubeRBACProxy.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ceems.exporter.fullname" . }}
  labels:
    {{- include "kube-ceems.exporter.labels" . | nindent 4 }}
rules:
{{- if eq .Values.ceemsExporter.kubeRBACProxy.enabled true  }}
  - apiGroups: [ "authentication.k8s.io" ]
    resources:
      - tokenreviews
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources:
      - subjectaccessreviews
    verbs: [ "create" ]
{{- end }}
{{- if and .Values.redfishProxy.enabled .Values.redfishProxy.kubeRBACProxy.enabled }}
  - apiGroups: [ "" ]
    resources:
      - services/{{ template "kube-ceems.redfish-proxy.fullname" . }}
    verbs: [ "get", "create" ]
{{- end }}
{{- if .Values.ceemsExporter.collectors.k8s.enabled }}
  - apiGroups: [ "" ]
    resources:
      - pods
    verbs: [ "get", "list", "watch" ]
{{- end }}
{{- with .Values.ceemsExporter.rbac.extraClusterRoleRules }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
