---

# This scenario uses mTLS for the CEEMS exporter so that
# any unauthorised access of CEEMS exporter can be
# avoided.


webConfig:
  # HTTP server web TLS config for CEEMS exporter
  tls_server_config:
    client_auth_type: RequireAndVerifyClientCert
    client_ca: |
      -----BEGIN CERTIFICATE-----
      MIIBxzCCAU2gAwIBAgIUGCNnsX0qd0HD7UaQsx67ze0UaNowCgYIKoZIzj0EAwIw
      DzENMAsGA1UEAwwEdGVzdDAgFw0yMTA4MjAxNDQ5MTRaGA8yMTIxMDcyNzE0NDkx
      NFowDzENMAsGA1UEAwwEdGVzdDB2MBAGByqGSM49AgEGBSuBBAAiA2IABLFRLjQB
      XViHUAEIsKglwb0HxPC/+CDa1TTOp1b0WErYW7Xcx5mRNEksVWAXOWYKPej10hfy
      JSJE/2NiRAbrAcPjiRv01DgDt+OzwM4A0ZYqBj/3qWJKH/Kc8oKhY41bzKNoMGYw
      HQYDVR0OBBYEFPRbKtRBgw+AZ0b6T8oWw/+QoyjaMB8GA1UdIwQYMBaAFPRbKtRB
      gw+AZ0b6T8oWw/+QoyjaMA8GA1UdEwEB/wQFMAMBAf8wEwYDVR0lBAwwCgYIKwYB
      BQUHAwIwCgYIKoZIzj0EAwIDaAAwZQIwZqwXMJiTycZdmLN+Pwk/8Sb7wQazbocb
      16Zw5mZXqFJ4K+74OQMZ33i82hYohtE/AjEAn0a8q8QupgiXpr0I/PvGTRKqLQRM
      0mptBvpn/DcB2p3Hi80GJhtchz9Z0OqbMX4S
      -----END CERTIFICATE-----
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIFsDCCA5igAwIBAgIRAMMSh5NoexSCjSvDRf1fpgMwDQYJKoZIhvcNAQELBQAw
      aTELMAkGA1UEBhMCVVMxEzARBgNVBAoTClByb21ldGhldXMxKTAnBgNVBAsTIFBy
      b21ldGhldXMgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRowGAYDVQQDExFQcm9tZXRo
      ZXVzIFRMUyBDQTAgFw0yMjA3MDgwOTE1MDdaGA8yMDcyMDYyNTA5MTUwN1owNjEL
      MAkGA1UEBhMCVVMxEzARBgNVBAoTClByb21ldGhldXMxEjAQBgNVBAMTCWxvY2Fs
      aG9zdDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANPl1Iv/z+M8jHHU
      SggOhvCS/0IfNi82+OprwalmhSL1FyRrGeHDpKArIrHhal7oukizJq96wKTddUVu
      hjPR7srSYX7J2oPznjb2FmLHnD8y+zxO83XNA5WCDB0yA/KhWHhDmd2pihTTZOo9
      jvGi3+LyIqXUeiwIpxuNnH2ghoUy+DTzNCknLkIKAVnDPoM1AI0Wu24rs14A8ZVW
      ivzY/P8xGwlMmDndrrHwJzMSEMeH7IJi9hx4zJalpoYTVq6Z0Rv0+7SpS+iswi/e
      MILDhmSvLw0R4x31xkzsPOtUsocVjgBCGGGHo70ISsAxsL6E9QFe2uwZSvbBKfou
      JaM0txRIZahMeHy5egh2+J08vuZKo9PDBWwKwqQZ4Kb7WtgekiycLmFa/OYHLUX+
      Ow8QXu5HU9v9XlP9GV2FQDka2IuMTtS5JCEt5e9ddSb4KVbkRAhfL2snA+w0nmrf
      CBlrlThFz5Evy5QNAo1ORwiE+8gNUc12EAu9K3TK9WSUYNrLCbkN3oBL+DVp8Y6q
      quUpKEbElhsJ9V49Err3LPaXpz5aW7Th6oFq7UOB7chqKQ2SNl3/hTlNUw8wFb9Q
      i8AXs+4SzHo41IEe9QZBvpeucVmdewbJKvNS8Uxs2wmtTq2G2Ae3qGzWl682J7aU
      w1X6Y46OanQDNtDVQvGN1CW5kvCXAgMBAAGjgYMwgYAwDgYDVR0PAQH/BAQDAgUg
      MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8G
      A1UdIwQYMBaAFMaaHh5g0+YopeLd1IkizXyK9K/zMCAGA1UdEQQZMBeCCWxvY2Fs
      aG9zdIcEfwAAAYcEfwAAADANBgkqhkiG9w0BAQsFAAOCAgEAUXL/lzbgbs6whVrE
      3wkp0oDGVZ0Jti1hpeQk7Slt3PHsgu9OQOSGcv9QHs0ybhkDWZQjoCH6Nurx5QaY
      GnpNQjylfy3zAziO0c7C1uXf7Z9AEMQwbOHFLefnvq86MtnwJ7sadQo+ViwtMgOW
      He4YhkTyu2CqK8GFXRQUNm/SunffXp5zErPCNQURh4hrDUGlXPzyxgx1DyqFvF4S
      X8IpsoED3d7cbEL7E9dgXNl7wuy3qoPi9P9KydFTIELBGt1oco980S1attSM9159
      t9iUIUMT4EdzmZxpIyJMCD+Lz9Y3zWVyz7DTqFWOtAtmhM4lu44K4S4d/JfAGEal
      3h3SMCbBPKwpsloO4r9TeGi2f+T7hfiFMdCezEyG8sXrObCDyVudyUnXnxDkZ5TQ
      NOzqJaUJHeKzb+Z9WSovce3Pb8ok3GoDugmwqyjuN/rz/0jsDTJm18I6HHtONbUp
      AIV/H/4+Kewc+Ztv97J7MeQB/2VKcY3vpZpMSEkg2ummRhXUfi0haxfoSCKvRwiD
      BElUVtwHTsn3OBnKMGcBt32iLVsvbb/0AtNpohznPdQT7dqDVguejmwHn/fc4u4Q
      vfAay/ACARti9XKGplQi7xn+OoYcAVPLYitYBRNEc6t+4f3EKehrDIMRCnxOFBVX
      9Dnm1DebturSQQEOuX5rP15lG1I=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDT5dSL/8/jPIxx
      1EoIDobwkv9CHzYvNvjqa8GpZoUi9Rckaxnhw6SgKyKx4Wpe6LpIsyavesCk3XVF
      boYz0e7K0mF+ydqD85429hZix5w/Mvs8TvN1zQOVggwdMgPyoVh4Q5ndqYoU02Tq
      PY7xot/i8iKl1HosCKcbjZx9oIaFMvg08zQpJy5CCgFZwz6DNQCNFrtuK7NeAPGV
      Vor82Pz/MRsJTJg53a6x8CczEhDHh+yCYvYceMyWpaaGE1aumdEb9Pu0qUvorMIv
      3jCCw4Zkry8NEeMd9cZM7DzrVLKHFY4AQhhhh6O9CErAMbC+hPUBXtrsGUr2wSn6
      LiWjNLcUSGWoTHh8uXoIdvidPL7mSqPTwwVsCsKkGeCm+1rYHpIsnC5hWvzmBy1F
      /jsPEF7uR1Pb/V5T/RldhUA5GtiLjE7UuSQhLeXvXXUm+ClW5EQIXy9rJwPsNJ5q
      3wgZa5U4Rc+RL8uUDQKNTkcIhPvIDVHNdhALvSt0yvVklGDaywm5Dd6AS/g1afGO
      qqrlKShGxJYbCfVePRK69yz2l6c+Wlu04eqBau1Dge3IaikNkjZd/4U5TVMPMBW/
      UIvAF7PuEsx6ONSBHvUGQb6XrnFZnXsGySrzUvFMbNsJrU6thtgHt6hs1pevNie2
      lMNV+mOOjmp0AzbQ1ULxjdQluZLwlwIDAQABAoICAQCxGs9jlBQ1YU4hdcXKphmy
      yan/ogavv8qcZCQhakasyRzmm32ubM8T7/m3oyg821eXm+Uhlf+dzFtQBOi2NyjW
      7LAAQMYas2vxlA1x0lSNnhbOeU6Tjx8HvwJRBJS4HpLLMfVQh3uZnHYkMf9fhzqJ
      fMfowoa6dyD0ro+1kI3elpNN7lgSbWUEXUhztfRxxcMIKY/OrUflsfQ5VXQlkVck
      E+78/r/c3aQ9pPOeg+LyYnETKZN6iJy27Q0Z0uAIXxefvksC3N1NQ9eqGpOBN9sE
      HEe/LMwfJmTvtiPUrZ3pueJN5PBr0+rO/Dc+HEoVcxs0Yguoehtl0l07dYaPumep
      TmXdrKvCkwM5cwnbXSWrCpqMS8Medb3zWvNnWO/mjRwTZyhmNdscjh3Ilvo+YCus
      wM8HJFD4FuMtL3GtIfoKeszppACTkOOYiViGHmKUiQaSEwF7nhuIQqgN3ULCP7Z5
      mhL2RhLWacPfATITNkm4g2o16mFohZ9HPZSkPGm8rw7yhB1s2emoocXsms2iR1oa
      mggNnUS3m87Z/HmOEyObIQZtYf1ZNuVAGGP4kmhhtNfMTmq3CPYM3oMRR1nb8Ci8
      zYwjEIvLYuDVlZFff4+IA7tCBZPichieoioaxutnYtO+nvuzDRiitL4my2EcXeE7
      tcIunkP9u5BNiXsfNcy3gQKCAQEA3X9eZ/IPF9Rrsjwtqkt7Oxn/uJ8JCotVBLnq
      SCd7sCSaM06jUzMjMoj4SYyjzBYLycH/q+euT4UoPdPMKCfwx2NgR87MfuehWzwG
      pmPbAbLJtLmZ+M/Bz5QzGS3J3f4qYxLptLHX971JgtTdcJhOAc+p/Elt3l43d/fr
      sMVrZ8hqHlXmA6WuwqHjHnGP1ML6xFfsjDZ2jQ3VEV17XKtinucgitvkVuHYmtdQ
      wm/yrM8vDkyglgk47j9CyfQdL10elBxe32WY5B0g9TmhIMypmlJk7inPPnAqJ4TF
      JJBMvZOB9cJAjrtsDN3tAW/1q+wPF1HLwurqTLluZEc5MVjaOQKCAQEA9OenKlxB
      5HiANjH0riaokFDtjC27iHoeBkbEt+CyegGXVHEotVcKnG+N4Tw/GXcS9m33vu/X
      Lmeowp/Z2BKxB7xvw81jQh8gEoUHFlH6DgksTPjVVSEa4wnESrqlFjRquBexpU6e
      X//xVD72b0txAqJvpvtbxZC41WIwUBTBkHDlj2hegEzUvgzdO92FPRUDrAgB0wSv
      05U6fh1/4c3XTHqIHK4/gxiVRmjnpEdjEbOZsfbN8LGQK2eq4FkIS870VKigUZ/U
      m2YB+8PKKyqKdXpWQHMZ9QvXoU9AwMw4Q+NEk4a/ZrnnMo59voKP1Qoqhd/rEAP7
      xa1AMOAl2DhhTwKCAQBdY4Z6bSTP91AxJg5a7thWYu/e967oMzb1dy3AnmUYL1aU
      q2NRgQ4mEHofCJ1HP0RZHOKfqF9mR85fwx0hETYD23KM1DSEjUULIpPrM87zOF6z
      RE4XCgG9c87XnuauIqvceezvssxMOBL2hqmW/6BkQxp4tL0ONMtOWcmWDqbqayXT
      BISmpQS6K2eHPnpWSp9QiYHC3HO/pUVgvPl2aQx70xd1dKEhwLeDEaWLVYgMNI6y
      iLxshhbq3OFcJQDpJ2ntKMkXh86e32k1+8Zj/ebEmljT0ez/dmtPnjtA31Z71+XD
      qNNvWraD9k4nfP0oL69tNZ+j30hKcSSKQz1qAPyBAoIBAGBaI3KPCX2Ryx+HV/SM
      URU2Qb883uM66EUf4pVVWeKWbatTOejebdZOLUvIICsspdE+QpJkWgxvy/2GVnak
      I/IfOPmX/M0u4bdnjvpBFlgfU8aUv5nWhHV+ijO8aubpiHMVH1ciLz0lvRSgEOSI
      kdWvgq33houb/Jw3HTrkb6McR7S8IzHnCGwdM40yAhGeCuvL2qvi1CoyM+kaQg3c
      pi/4pURjaalyKoihDUGctGVqe7WAnFVuBoKNLrVFUfZBXe9QyIJUl5jr8SvUQ93n
      xsGhd/2zSysVlahpPdicgCZ1a61+/h60VTmWxfIF/ACdF03EYv7SEmQbXX3dMgZ3
      aBECggEBALXqdEIkb9pBhwCvUHFG+c/IKBhS6j7BUj9PrZ3MATPXHo6Iy09d/dlV
      psFQzWVvBmf3pcI0MEi7xdUMSN0jhZ8xp1owDlOQSM8DCQPFLaC38sfhZNThIfz0
      Q+fWYPe1lkRBtMVSokN1PtE5zETHlUKkh3fdQs0wihX4Wikc64rjCgXqXc8ng8Lk
      NCUNBY/7pNfrEm0Zxz+8CvmRaBbL4OT2/hFsdcMiO3P24mCdAPgJ4v97pr8KxRHe
      SmOyiSdaAyXHr/6+3KgO5pX8YUn9WiTF2hxo4SG3NQuuva0SBZT9B8iFXt1uFUtP
      Rri7hsjysanKPyaPM1oofbRyWApMyRo=
      -----END PRIVATE KEY-----

# Client TLS credentials are created in a secret which are referenced below
extraManifests:
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: ceems-exporter-tls-client-config
      namespace: {{ include "ceems-exporter.namespace" . }}
      labels:
        {{- include "ceems-exporter.labels" . | nindent 4 }}
    data:
      ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYxRENDQTd5Z0F3SUJBZ0lSQU1NU2g1Tm9leFNDalN2RFJmMWZwZ0l3RFFZSktvWklodmNOQVFFTEJRQXcKYWpFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBb1RDbEJ5YjIxbGRHaGxkWE14S1RBbkJnTlZCQXNUSUZCeQpiMjFsZEdobGRYTWdRMlZ5ZEdsbWFXTmhkR1VnUVhWMGFHOXlhWFI1TVJzd0dRWURWUVFERXhKUWNtOXRaWFJvClpYVnpJRkp2YjNRZ1EwRXdJQmNOTWpJd056QTRNRGt4TlRBMldoZ1BNakEzTWpBMk1qVXdPVEUxTURaYU1Ha3gKQ3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRS0V3cFFjbTl0WlhSb1pYVnpNU2t3SndZRFZRUUxFeUJRY205dApaWFJvWlhWeklFTmxjblJwWm1sallYUmxJRUYxZEdodmNtbDBlVEVhTUJnR0ExVUVBeE1SVUhKdmJXVjBhR1YxCmN5QlVURk1nUTBFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURYdFViWmhIUjIKeEVseUdKK0J3Y1poNGhtNGRoMU9obEo2Zzk4SDJyRU9LNmJCeGVPNVlabnRoZkNuSEk2V1lOMjcweWx1c1VjNgpKVmt1VS8xUE83TkxZc2wxRDRaSXJSS1FCV2ZnODhCWXJETzM4SFVrcm00YW9obHBUMCtmN1NpQTdlUmwxTWI1Cng2Zmk1QkFWRTV3blFKVEU4VlBCVStsWEpCK1NmWkVpeHUrbzFQbHhWQWRNWVBBdTFZaWpha3IxbER1WmV4Ky8Kai83MDBtaWhTQWN3T3ZKLytwNHUyV05qMENNdlFXaVY1K1ZCWllyZnBSTjQvMjAxRm95V0lMSXYzSExxNU9LcApCcGwvVHZKNEo4b0cxQ2J6am01MnFMZ1VPdkhrQUowSTA0RHhXV3l3SEYwVlJ1bXdMU3FhZTB4bytLUFBpamo3CmJkbkN4K3Z5MzdQYkZPZ2h6S3pTSWJQdWNjZktpdlZwQ2hneTluMGtrZ1FobTljZ0ZFNVNCdU82amZSd3RvMGcKZHJTT01JenlYRUxERzBoMG5CMmdzUFVIakQvT0QxRFQwVnNXLzl4WE9QQmZWZ3RQRm41TG9aOG5pbkFGbWsycgpaaVJKaENYaGgrUmx3MkYvczJTVFA2NlJuVUdWZGZQMnN5VitVbGdKbEU3RVBFOGNEYnlmUXFnN0ZUZmxxK3QrCkhnWEZDQWtKNFMzNCsvcUNiR3YzRGxibkMxbHErRmlWd2V4bTFUY2ZML2xZZmhQci9KNlZvZUZadzRialRQTmEKalVJTHBzWHY2SVF6Z1BmQ0J4ZVpDNmREa0sxRDBjRVhBcVJSWUtFRnhkTG5NakJjVVpsV1VWOXVUdWswMWZEYwo1OGJtbEh0NXNFcWhjZFVxSHJSNVBkb1dKVk9TYkZ3WUJ3SURBUUFCbzNRd2NqQU9CZ05WSFE4QkFmOEVCQU1DCkFxUXdEd1lEVlIwbEJBZ3dCZ1lFVlIwbEFEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVEcKbWg0ZVlOUG1LS1hpM2RTSklzMThpdlN2OHpBZkJnTlZIU01FR0RBV2dCUkpQckVPbTJack1ncjlBRlR6OUxaeQowZkROTmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQW9jME9JbWN5eUtTYlZLNjNRQThWbUQybzlYcjdhYnhYCm8rZitRWFdEcUtBbE5EQXVYTFlCakhNQ2M5WUZzeFhhOVhrdUtaZUl4em9wNGg5aUdHK2Z4TVZQVHgzVDBnVG0KTUF1SGNQa2ExMHo0R3k2WnhMekRteEpQa0o0NmIxbjBLMmZzdjlYc2h6c0hFUnozVmF2d0hYYkM1bUJvMUN3SQo2eExMdFRXTXVKZG95dDAyNjFEN0RhdDFKQUZJV20yaitreEd2eUlQMGdOdFJzVUtPRkEyMlRsdDQyc0VZblhhCjd3bVk3YjE1cm5kRzY5WGc5WmlWSTVNYi8xMGdESlFjeW0yM1BYUm4rSkVnc3NFK1djWWhsbDhmL0xSbUQ0OXYKWmxCQkQxZFZvYzlKeXJnVCtBbisyWjhsRTZ3Q1NQcVdTd2h6dkJXNGR5Qi91N0puMjNkbFYxU3dKUjh4L0lhVwpqL0RoQ0VMTnFENmNTbFJLM3lqRS9hMi9pSzBGNnBOclZnS0RZKy85dXdGeHdraklSd3FmY0Z0VDZZcFozM21nCmtTZFRUYllwZWczWGtMWVpheUUzbnR6RWhvb3lRZHJKUjZZeUZWd3NnY0JDa2VMckViQzd5L0FHMU1RRWRLc1oKaTNxNzMwdnp0R1FCUjF5bVB3Z2JCNnF6R09YaG1uaEpIblFqZVAyQ0pXbnpEZU9oMlZzNEN4TEFRWkovZGhZZApxcmJZUEFUOEZKa3AyUHZvSlA4enBtRDdhOFFDKzZHcjE3a2w5T3VwUFFySUlmeENYWVpLRGRHT2xrRFNVQzE2CjZ5MEUxV1puSStMVmJRQjFNNTg0bEIyLzhqVTR4cU1xVVBmb0ljYmpramloOW52VkE2dDU0NzUyN01lZVR2WFQKMGlnMlF2TUZXTXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ0RENDQTV5Z0F3SUJBZ0lSQU1NU2g1Tm9leFNDalN2RFJmMWZwZ0V3RFFZSktvWklodmNOQVFFTEJRQXcKYWpFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBb1RDbEJ5YjIxbGRHaGxkWE14S1RBbkJnTlZCQXNUSUZCeQpiMjFsZEdobGRYTWdRMlZ5ZEdsbWFXTmhkR1VnUVhWMGFHOXlhWFI1TVJzd0dRWURWUVFERXhKUWNtOXRaWFJvClpYVnpJRkp2YjNRZ1EwRXdJQmNOTWpJd056QTRNRGt4TlRBMFdoZ1BNakEzTWpBMk1qVXdPVEUxTURSYU1Hb3gKQ3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRS0V3cFFjbTl0WlhSb1pYVnpNU2t3SndZRFZRUUxFeUJRY205dApaWFJvWlhWeklFTmxjblJwWm1sallYUmxJRUYxZEdodmNtbDBlVEViTUJrR0ExVUVBeE1TVUhKdmJXVjBhR1YxCmN5QlNiMjkwSUVOQk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBcmt6UlBpMjEKRTI5OXZYdzRGQmJNZkNYSTI1OFN4dnZqUlZSdUtkQUhMT0JwRUVxa1lINnI2U2NiWmFpc0JGdEllUHY0ZGRLbApybXYrbkR3Tjg0L0tTNTRPT3R3MWNXRDRBbkRCMGtMM0IwcFdYalRTMUYvdTU3aFJMeE02VGEwVXViS2J0YS9oCldxU09SL2ZBQTVzZ2NsK0piYlI2MVFXVmVZWVhnOWJNOFlHVHdRTWVKb2QyNnRJVWVYL1JlbzlCSHVpVzRqUGIKcHZWZjdyc09zOEUyY0d3ZllqWnU2WmoycWNDeFEvaXZDcG9wS0ZMTmxhS2tvL0tsR0RHejlLeEs1WDNpaytzRQpmUEs5THpMQzBrMlJMR2MzRW1jTWtkeXFFM1ZOaWg5blY5U2FsQVhONXlCZFlhV1dqSlh5a3R5N2lsVTMyTUJGCnlPNG15TDQ4dmlmMks2OHBEL0NGaEc4WW1JT3VkM3dvTW0xSVlTOXhsc1lLZjcrZjVDTmx4cXorZVNvT0doY0cKZFNETmZ0M2g1bnVxOUovcWIycklnV01TYzJwdUZOUnN4K2ZpczBrUzVHdmpWYWRSMGx4dEFyYnJObTRTK0YyMgpFakd4ZUJGNVZJV2l1MzF1cHBiZEFTSXc2RFRLY3JTVlZvV3hxK0ZrM09PQis3cStyb3Jub3NvcDlhL29tWEdICjBjVG1nYXJqSnRNcWEwVEVRaVVQUVBQbm1wQzFqb2VDNy9raDdha3M5M3dmSHRZNzN1QVZuVGpMR1RPd2xyNTAKQ2dSU2hjUm9MTE4wNDlWOTNsNDZBRkhVLzRIV25zOGRxZ2RjZEdudklkVUNGaWs5MTZwS0RTdkVjL0RmTUxHaApINnc5WGxnNCsyTGdDeUcyL0ZCRU1UaitiTG9yYXlkenlhRUNBd0VBQWFOVE1GRXdEZ1lEVlIwUEFRSC9CQVFECkFnS2tNQThHQTFVZEpRUUlNQVlHQkZVZEpRQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKU1Q2eERwdG1heklLL1FCVTgvUzJjdEh3elRZd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFITTc5Ui91UXdRWAp2c0JEZkt5QlhXRmxyaEhBZ1g4WEF3TUtIanN0cFFZQ2NKb2lHTFJKYU1NanhqMzFUMXR5bHFQZGN4ejg4VEhOCnVqOWtWRllNbzFHVTVLOUU5bHEwTG9XUUJtWDJSNy9SZ3hXcUI3Rk5TK1MweGZHeWVVYjNZUFZQSTF5aHRzS2EKNm1DdFR1Q1Znc2dzL2hUYSt1bWp0ZmZ4ajdsK0lReEQ4RnEwUkZCYWUrUzB2NW1qVkMyc1VWZDZ1c3FWdDdGNgpMVVZ1WVNoeUFJNzA1Z3VJVjlua3o4WnlMelVCSm5RQUo4ZzZEVStuTG1kaXppZ1VHK0pvRC9oQmJLMmh2Y2pYClNMN0pMQWhZUkk0a3pXY1lSMEdVZkRmMmtuRkVXTmhVOGdDUG53NzBGSE1EOVFDM05La1FzUHZ5UVJ5Smg5OSsKaXB3VUZiR0pKUllXakZCYlV4bHFaTnFCZzYreWxaTkZHRW5HNDJ1Mkt2UFhqZ1BkaXZsUVdrclg2bkcwYXl5bApyWXJ2aTBGYXdQM09CcENyaFlocXNxa0EybSs1TDJQbCtKMlNzRHY0cW1QQjZmaDdLMFlEVkIzN0FaU0crbmZMCm9YWHBVdHdmYzl0UjcxUzdHbWdrY3FZT2tIZlN6bDdlY3hYdEUyeHlsM3poa1VQUjlZY0crclFoWFJScDBseEYKa1IwRXRHT0d1dlhNQ1EvdkJWUE5FRFMzamRjZXFJcklSSTF5UFVkaEZrRjdsckxzZkZVTGxsT3Q2cVFXbmhuMgpBMk9ieEhUb29od3V5cmkvdjhRaHFOSTJCZzBqSkhjQUppOEk4dGFUb0FzdENXcnRuK1dYeWZqL1FrbkFpazQ3CmFPSzlsNXdTeXlxUGZrSHliS3ZUNno5cHFXVWNoSnN6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
      cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ4ekNDQVUyZ0F3SUJBZ0lVR0NObnNYMHFkMEhEN1VhUXN4Njd6ZTBVYU5vd0NnWUlLb1pJemowRUF3SXcKRHpFTk1Bc0dBMVVFQXd3RWRHVnpkREFnRncweU1UQTRNakF4TkRRNU1UUmFHQTh5TVRJeE1EY3lOekUwTkRreApORm93RHpFTk1Bc0dBMVVFQXd3RWRHVnpkREIyTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQTJJQUJMRlJMalFCClhWaUhVQUVJc0tnbHdiMEh4UEMvK0NEYTFUVE9wMWIwV0VyWVc3WGN4NW1STkVrc1ZXQVhPV1lLUGVqMTBoZnkKSlNKRS8yTmlSQWJyQWNQamlSdjAxRGdEdCtPendNNEEwWllxQmovM3FXSktIL0tjOG9LaFk0MWJ6S05vTUdZdwpIUVlEVlIwT0JCWUVGUFJiS3RSQmd3K0FaMGI2VDhvV3cvK1FveWphTUI4R0ExVWRJd1FZTUJhQUZQUmJLdFJCCmd3K0FaMGI2VDhvV3cvK1FveWphTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RXdZRFZSMGxCQXd3Q2dZSUt3WUIKQlFVSEF3SXdDZ1lJS29aSXpqMEVBd0lEYUFBd1pRSXdacXdYTUppVHljWmRtTE4rUHdrLzhTYjd3UWF6Ym9jYgoxNlp3NW1aWHFGSjRLKzc0T1FNWjMzaTgyaFlvaHRFL0FqRUFuMGE4cThRdXBnaVhwcjBJL1B2R1RSS3FMUVJNCjBtcHRCdnBuL0RjQjJwM0hpODBHSmh0Y2h6OVowT3FiTVg0UwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JRzJBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQklHZU1JR2JBZ0VCQkREbW9UeFljQmZScnFZYi9USnkKb0hsQktvNC9mTmsyTEJVWnhwQzNIZUthc0FRelM5QUIxZXZ3M2s0TTNQZThjNCtoWkFOaUFBU3hVUzQwQVYxWQpoMUFCQ0xDb0pjRzlCOFR3di9nZzJ0VTB6cWRXOUZoSzJGdTEzTWVaa1RSSkxGVmdGemxtQ2ozbzlkSVg4aVVpClJQOWpZa1FHNndIRDQ0a2I5TlE0QTdmanM4RE9BTkdXS2dZLzk2bGlTaC95blBLQ29XT05XOHc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

prometheus:
  monitor:
    scheme: https
    # HTTP client TLS config for Prometheus to connect to CEEMS exporter
    tlsConfig:
      ca:
        secret:
          name: ceems-exporter-tls-client-config
          key: ca
      cert:
        secret:
          name: ceems-exporter-tls-client-config
          key: cert
      keySecret:
        name: ceems-exporter-tls-client-config
        key: key
      insecureSkipVerify: true
