{{- if.Values.rbac.create }}
{{- if or .Values.kubeRBACProxy.enabled .Values.monitorCurrentCluster (gt (len .Values.rbac.extraClusterRoleRules) 0) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceems-api-server.fullname" . }}
  labels:
    {{- include "ceems-api-server.labels" . | nindent 4 }}
rules:
{{- if eq .Values.kubeRBACProxy.enabled true  }}
  - apiGroups: [ "authentication.k8s.io" ]
    resources:
      - tokenreviews
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources:
      - subjectaccessreviews
    verbs: [ "create" ]
{{- end }}
{{- if .Values.monitorCurrentCluster }}
  - apiGroups: [ "" ]
    resources:
      - pods
      - rolebindings
    verbs: [ "get", "list", "watch" ]
{{- end }}
{{- with .Values.rbac.extraClusterRoleRules }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
