apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "ceems-api-server.fullname" . }}-config
  namespace: {{ include "ceems-api-server.namespace" . }}
data:
  config.yaml: {{ include "ceems-api-server.config" . | b64enc }}
