{{- $sts := list "sts" "StatefulSet" "statefulset" -}}
{{- if (and .Values.persistence.enabled (not .Values.persistence.existingClaim) (has .Values.persistence.type $sts))}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ceems-api-server.fullname" . }}
  namespace: {{ include "ceems-api-server.namespace" . }}
  labels:
    {{- include "ceems-api-server.labels" . | nindent 4 }}
  {{- with .Values.deployAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ceems-api-server.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ceems-api-server.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ceems-api-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- include "ceems-api-server.pod" . | nindent 6 }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: storage
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- with .Values.persistence.volumeName }}
      volumeName: {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- with .Values.persistence.selectorLabels }}
      selector:
        matchLabels:
          {{- toYaml . | nindent 10 }}
      {{- end }}
  {{- end }}
{{- end }}
