{{/*
.Chart.IsRoot is not documented.
Ref: https://github.com/helm/helm/pull/9993
*/}}
{{- if .Chart.IsRoot }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "ceems-lb.fullname" . }}-config
  namespace: {{ include "ceems-lb.namespace" . }}
data:
  config.yaml: {{ include "ceems-lb.config" . | b64enc }}
{{- end }}
