{{/*
.Chart.IsRoot is not documented.
Ref: https://github.com/helm/helm/pull/9993
*/}}
{{- if .Chart.IsRoot }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ceems-lb.fullname" . }}
  namespace: {{ include "ceems-lb.namespace" . }}
  labels:
    {{- include "ceems-lb.labels" . | nindent 4 }}
  {{- with .Values.deployAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ceems-lb.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ceems-lb.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ ternary true false (or .Values.serviceAccount.automountServiceAccountToken .Values.kubeRBACProxy.enabled) }}
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ceems-lb.serviceAccountName" . }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        {{- $servicePortTSDB := ternary .Values.kubeRBACProxy.port .Values.service.port .Values.kubeRBACProxy.enabled }}
        {{- $servicePortPyro := add $servicePortTSDB 10 }}
        - name: lb
          image: {{ include "ceems-lb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/ceems_lb
          args:
            - --web.listen-address=[$(HOST_IP)]:{{ $servicePortTSDB }}
            {{- if (contains "pyroscope" (include "ceems-lb.backend-types" .)) }}
            - --web.listen-address=[$(HOST_IP)]:{{ $servicePortPyro }}
            {{- end }}
            - --config.file=/etc/ceems-lb/config.yaml
            {{- if not (empty .Values.webConfig) }}
            - --web.config.file=/etc/ceems-web/config.yaml
            {{- end }}
            {{- range $_, $arg := .Values.additionalArgs }}
            {{- if (hasKey $arg "value") }}
            - --{{ $arg.name }}={{ $arg.value }}
            {{- else }}
            - --{{ $arg.name }}
            {{- end }}
            {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              {{- if .Values.kubeRBACProxy.enabled }}
              value: 127.0.0.1
              {{- else if .Values.service.listenOnAllInterfaces }}
              value: 0.0.0.0
              {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
              {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if eq .Values.kubeRBACProxy.enabled false }}
          ports:
            - name: {{ printf "%s-tsdb" .Values.service.portName | trunc 14 }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if (contains "pyroscope" (include "ceems-lb.backend-types" .)) }}
            - name: {{ printf "%s-pyroscope" .Values.service.portName | trunc 14 }}
              containerPort: {{ add .Values.service.port 10 }}
              protocol: TCP
            {{- end }}
          {{- end }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_lb
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_lb
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationMessageParams.enabled }}
          {{- with .Values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: ceems-lb-config
              mountPath: /etc/ceems-lb
            {{- if not (empty .Values.webConfig) }}
            - name: ceems-lb-web-config
              mountPath: /etc/ceems-web
            {{- end }}
            {{- if ne .Values.ceemsAPIServer.persistenceVolumeClaim "" }}
            - name: ceems-db
              mountPath: /var/lib/ceems_api_server
            {{- end }}
            {{- range $_, $mount := .Values.extraHostVolumeMounts }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
              readOnly: {{ $mount.readOnly }}
              {{- with $mount.mountPropagation }}
              mountPropagation: {{ . }}
              {{- end -}}
            {{- end -}}
            {{- range $_, $mount := .Values.configmaps }}
            - name: {{ tpl $mount.name $ | quote}}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
            {{- range $_, $mount := .Values.secrets }}
            - name: {{ tpl $mount.name $ | quote }}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{-  if .Values.kubeRBACProxy.enabled  }}
        - name: kube-rbac-proxy-tsdb
          args:
            {{- range $_, $arg := .Values.kubeRBACProxy.additionalArgs }}
            {{- if (hasKey $arg "value") }}
            - --{{ $arg.name }}={{ $arg.value }}
            {{- else }}
            - --{{ $arg.name }}
            {{- end }}
            {{- end }}
            - --secure-listen-address=:{{ .Values.service.port}}
            - --upstream=http://127.0.0.1:{{ $servicePortTSDB }}/
            - --proxy-endpoints-port={{ .Values.kubeRBACProxy.proxyEndpointsPort }}
            - --config-file=/etc/kube-rbac-proxy-config/config-file.yaml
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - --tls-cert-file=/tls/private/{{ .Values.tlsSecret.certItem }}
            - --tls-private-key-file=/tls/private/{{ .Values.tlsSecret.keyItem }}
            {{- if and .Values.kubeRBACProxy.tls.tlsClientAuth .Values.tlsSecret.caItem }}
            - --client-ca-file=/tls/private/{{ .Values.tlsSecret.caItem }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: kube-rbac-proxy-config
              mountPath: /etc/kube-rbac-proxy-config
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - name: {{ tpl .Values.tlsSecret.volumeName . | quote }}
              mountPath: /tls/private
              readOnly: true
            {{- end }}
            {{- with .Values.kubeRBACProxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.kubeRBACProxy.image.pullPolicy }}
          {{- if .Values.kubeRBACProxy.image.sha }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}@sha256:{{ .Values.kubeRBACProxy.image.sha }}"
          {{- else }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ printf "%s-tsdb" .Values.kubeRBACProxy.portName | trunc 14 }}
              {{- if .Values.kubeRBACProxy.enableHostPort }}
              hostPort: {{ .Values.service.port }}
              {{- end }}
            - containerPort: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              {{- if .Values.kubeRBACProxy.enableProxyEndpointsHostPort }}
              hostPort: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              {{- end }}
              name: {{ trunc 14 "http-healthz-tsbd" }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              path: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- if .Values.kubeRBACProxy.resources }}
          resources:
          {{- toYaml .Values.kubeRBACProxy.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationMessageParams.enabled }}
          {{- with .Values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          {{- with .Values.kubeRBACProxy.env }}
          env:
            {{- range $key, $value := $.Values.kubeRBACProxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.kubeRBACProxy.containerSecurityContext }}
          securityContext:
          {{- toYaml .Values.kubeRBACProxy.containerSecurityContext | nindent 12 }}
          {{- end }}
        {{- if (contains "pyroscope" (include "ceems-lb.backend-types" .)) }}
        {{- $servicePort := add .Values.service.port 10 }}
        {{- $proxyPort := add .Values.kubeRBACProxy.proxyEndpointsPort 10 }}
        - name: kube-rbac-proxy-pyroscope
          args:
            {{-  if .Values.kubeRBACProxy.extraArgs  }}
            {{- .Values.kubeRBACProxy.extraArgs | toYaml | nindent 12 }}
            {{-  end  }}
            - --secure-listen-address=:{{ $servicePort }}
            - --upstream=http://127.0.0.1:{{ $servicePortPyro }}/
            - --proxy-endpoints-port={{ $proxyPort }}
            - --config-file=/etc/kube-rbac-proxy-config/config-file.yaml
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - --tls-cert-file=/tls/private/{{ .Values.tlsSecret.certItem }}
            - --tls-private-key-file=/tls/private/{{ .Values.tlsSecret.keyItem }}
            {{- if and .Values.kubeRBACProxy.tls.tlsClientAuth .Values.tlsSecret.caItem }}
            - --client-ca-file=/tls/private/{{ .Values.tlsSecret.caItem }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: kube-rbac-proxy-config
              mountPath: /etc/kube-rbac-proxy-config
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - name: {{ tpl .Values.tlsSecret.volumeName . | quote }}
              mountPath: /tls/private
              readOnly: true
            {{- end }}
            {{- with .Values.kubeRBACProxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.kubeRBACProxy.image.pullPolicy }}
          {{- if .Values.kubeRBACProxy.image.sha }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}@sha256:{{ .Values.kubeRBACProxy.image.sha }}"
          {{- else }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}"
          {{- end }}
          ports:
            - containerPort: {{ $servicePort }}
              name: {{ printf "%s-pyroscope" .Values.kubeRBACProxy.portName | trunc 14 }}
              {{- if .Values.kubeRBACProxy.enableHostPort }}
              hostPort: {{ $servicePort }}
              {{- end }}
            - containerPort: {{ $proxyPort }}
              {{- if .Values.kubeRBACProxy.enableProxyEndpointsHostPort }}
              hostPort: {{ $proxyPort }}
              {{- end }}
              name: {{ trunc 14 "http-healthz-pyroscope" }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ $proxyPort }}
              path: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- if .Values.kubeRBACProxy.resources }}
          resources:
          {{- toYaml .Values.kubeRBACProxy.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationMessageParams.enabled }}
          {{- with .Values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          {{- with .Values.kubeRBACProxy.env }}
          env:
            {{- range $key, $value := $.Values.kubeRBACProxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.kubeRBACProxy.containerSecurityContext }}
          securityContext:
          {{ toYaml .Values.kubeRBACProxy.containerSecurityContext | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- if or .Values.imagePullSecrets .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "ceems-lb.imagePullSecrets" (dict "Values" .Values.ceemsLB "imagePullSecrets" .Values.imagePullSecrets) | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ceems-lb-config
          secret:
            secretName: {{ template "ceems-lb.fullname" . }}-config
        {{- if not (empty .Values.webConfig) }}
        - name: ceems-lb-web-config
          secret:
            secretName: {{ template "ceems-lb.fullname" . }}-web-config
        {{- end }}
        {{- if ne .Values.ceemsAPIServer.persistenceVolumeClaim "" }}
        - name: ceems-db
          persistentVolumeClaim:
            claimName: {{ tpl .Values.ceemsAPIServer.persistenceVolumeClaim . }}
            readOnly: true
        {{- end }}
        {{- range $_, $mount := .Values.extraHostVolumeMounts }}
        - name: {{ $mount.name }}
          hostPath:
            path: {{ $mount.hostPath }}
            {{- with $mount.type }}
            type: {{ . }}
            {{- end }}
        {{- end -}}
        {{- range $_, $mount := .Values.configmaps }}
        - name: {{ tpl $mount.name $ | quote }}
          configMap:
            name: {{ tpl $mount.name $ | quote }}
        {{- end }}
        {{- range $_, $mount := .Values.secrets }}
        - name: {{ tpl $mount.name $ | quote }}
          secret:
            secretName: {{ tpl $mount.name $ | quote }}
        {{- end }}
        {{- if .Values.kubeRBACProxy.enabled }}
        - name: kube-rbac-proxy-config
          configMap:
            name: {{ template "ceems-lb.fullname" . }}-rbac-config
        {{- end }}
        {{- if .Values.tlsSecret.enabled }}
        - name: {{ tpl .Values.tlsSecret.volumeName . | quote }}
          secret:
            secretName: {{ tpl .Values.tlsSecret.secretName . | quote }}
            items:
              - key: {{ required "Value tlsSecret.certItem must be set." .Values.tlsSecret.certItem | quote }}
                path: {{ .Values.tlsSecret.certItem | quote }}
              - key: {{ required "Value tlsSecret.keyItem must be set." .Values.tlsSecret.keyItem | quote }}
                path: {{ .Values.tlsSecret.keyItem | quote }}
              {{- if .Values.tlsSecret.caItem }}
              - key: {{ .Values.tlsSecret.caItem | quote }}
                path: {{ .Values.tlsSecret.caItem | quote }}
              {{- end }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
