{{- if .Values.rbac.create }}
{{- if or .Values.kubeRBACProxy.enabled .Values.collectors.k8s.enabled (gt (len .Values.rbac.extraClusterRoleRules) 0) (and .Values.redfishProxy.enabled .Values.redfishProxy.kubeRBACProxy.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceems-exporter.fullname" . }}
  labels:
    {{- include "ceems-exporter.labels" . | nindent 4 }}
rules:
{{- if eq .Values.kubeRBACProxy.enabled true  }}
  - apiGroups: [ "authentication.k8s.io" ]
    resources:
      - tokenreviews
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources:
      - subjectaccessreviews
    verbs: [ "create" ]
{{- end }}
{{- if and .Values.redfishProxy.enabled .Values.redfishProxy.kubeRBACProxy.enabled }}
  - apiGroups: [ "" ]
    resources:
      - services/{{ template "ceems-exporter.redfish-proxy.fullname" . }}
    verbs: [ "get", "create" ]
{{- end }}
{{- if .Values.collectors.k8s.enabled }}
  - apiGroups: [ "" ]
    resources:
      - pods
    verbs: [ "get", "list", "watch" ]
{{- end }}
{{- with .Values.rbac.extraClusterRoleRules }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
