apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ceems-exporter.fullname" . }}
  namespace: {{ include "ceems-exporter.namespace" . }}
  labels:
    {{- include "ceems-exporter.labels" . | nindent 4 }}
  {{- with .Values.daemonsetAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ceems-exporter.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ceems-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ ternary true false (or .Values.serviceAccount.automountServiceAccountToken .Values.kubeRBACProxy.enabled) }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ceems-exporter.serviceAccountName" . }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        {{- $servicePort := ternary .Values.kubeRBACProxy.port .Values.service.port .Values.kubeRBACProxy.enabled }}
        - name: ceems-exporter
          image: {{ include "ceems-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/ceems_exporter
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.cgroupfs=/host/sys/fs/cgroup
            - --web.listen-address=[$(HOST_IP)]:{{ $servicePort }}
            {{- if eq .Values.collectors.k8s.enabled true }}
            - --collector.k8s
            - --collector.k8s.kubelet-socket-file={{ .Values.collectors.k8s.kubeletSocketDirectory }}/kubelet.sock
            {{- end }}
            {{- if eq .Values.collectors.slurm.enabled true }}
            - --collector.slurm
            {{- if ne .Values.collectors.slurm.configDirectory "" }}
            - --collector.slurm.gres-config-file={{ .Values.collectors.slurm.configDirectory }}/gres.conf
            {{- end }}
            {{- end }}
            {{- if eq .Values.collectors.ipmi.enabled true }}
            - --collector.ipmi
            - --collector.ipmi.dev-num={{ (split "/dev/ipmi" .Values.collectors.ipmi.device)._1 | trim }}
            {{- if eq .Values.collectors.ipmi.monitorPowerEnergySensorReadings true }}
            - --collector.ipmi.power-energy-sensor-readings
            {{- end }}
            {{- range $key, $value := .Values.collectors.ipmi.monitorSensorIDs }}
            - --collector.ipmi.sensor-id={{ $value }}
            {{- end }}
            {{- end }}
            {{- if eq .Values.collectors.redfish.enabled true }}
            - --collector.redfish
            - --collector.redfish.web-config=/etc/redfish/config.yaml
            {{- end }}
            {{- if eq .Values.collectors.hwmon.enabled true }}
            - --collector.hwmon
            {{- end }}
            {{- if eq .Values.collectors.crayPMC.enabled true }}
            - --collector.cray_pm_counters
            {{- end }}
            {{- if eq .Values.collectors.rapl.enabled true }}
            - --collector.rapl
            {{- end }}
            {{- if eq .Values.eBPFProfiling.enabled true }}
            - --profiling.ebpf
            - --profiling.ebpf.config.file=/etc/profiling/config.yaml
            - --security.run-as-user=root
            {{- end }}
            {{- if not (empty .Values.webConfig) }}
            - --web.config.file=/etc/ceems-web/config.yaml
            {{- end }}
            {{- range $_, $arg := .Values.additionalArgs }}
            {{- if (hasKey $arg "value") }}
            - --{{ $arg.name }}={{ $arg.value }}
            {{- else }}
            - --{{ $arg.name }}
            {{- end }}
            {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              {{- if .Values.kubeRBACProxy.enabled }}
              value: 127.0.0.1
              {{- else if .Values.service.listenOnAllInterfaces }}
              value: 0.0.0.0
              {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
              {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if eq .Values.kubeRBACProxy.enabled false }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_exporter
                - -p
                - {{ $servicePort | quote }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_exporter
                - -p
                - {{ $servicePort | quote }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationMessageParams.enabled }}
          {{- with .Values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              {{- with .Values.hostProcFsMount.mountPropagation }}
              mountPropagation: {{ . }}
              {{- end }}
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              {{- with .Values.hostSysFsMount.mountPropagation }}
              mountPropagation: {{ . }}
              {{- end }}
              readOnly: true
            {{- if .Values.hostRootFsMount.enabled }}
            - name: root
              mountPath: /host/root
              {{- with .Values.hostRootFsMount.mountPropagation }}
              mountPropagation: {{ . }}
              {{- end }}
              readOnly: true
            {{- end }}
            {{- range $_, $mount := .Values.extraHostVolumeMounts }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
              readOnly: {{ $mount.readOnly }}
              {{- with $mount.mountPropagation }}
              mountPropagation: {{ . }}
              {{- end -}}
            {{- end -}}
            {{- if eq .Values.collectors.ipmi.enabled true }}
            - name: ipmi
              mountPath: {{ .Values.collectors.ipmi.device }}
              readOnly: false
            {{- end }}
            {{- if eq .Values.collectors.k8s.enabled true }}
            - name: pod-resources
              mountPath: {{ .Values.collectors.k8s.kubeletSocketDirectory }}
              readOnly: false
            {{- end }}
            {{- if and (eq .Values.collectors.slurm.enabled true) (ne .Values.collectors.slurm.configDirectory "") }}
            - name: slurm-config
              mountPath: {{ .Values.collectors.slurm.configDirectory }}
              readOnly: true
            {{- end }}
            {{- if eq .Values.collectors.libvirt.enabled true }}
            - name: persistent-qemu-xml-dir
              mountPath: /etc/libvirt/qemu
              readOnly: true
            - name: runtime-qemu-xml-dir
              mountPath: /run/libvirt/qemu
              readOnly: true
            {{- end }}
            {{- if eq .Values.collectors.redfish.enabled true }}
            - name: redfish-config
              mountPath: /etc/redfish
            {{- end }}
            {{- if eq .Values.eBPFProfiling.enabled true }}
            - name: profiling-config
              mountPath: /etc/profiling
            {{- end }}
            {{- if not (empty .Values.webConfig) }}
            - name: ceems-exporter-web-config
              mountPath: /etc/ceems-web
            {{- end }}
            {{- range $_, $mount := .Values.configmaps }}
            - name: {{ tpl $mount.name $ | quote}}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
            {{- range $_, $mount := .Values.secrets }}
            - name: {{ tpl $mount.name $ | quote }}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.kubeRBACProxy.enabled }}
        - name: kube-rbac-proxy
          args:
            {{- range $_, $arg := .Values.kubeRBACProxy.additionalArgs }}
            {{- if (hasKey $arg "value") }}
            - --{{ $arg.name }}={{ $arg.value }}
            {{- else }}
            - --{{ $arg.name }}
            {{- end }}
            {{- end }}
            - --secure-listen-address=:{{ .Values.service.port }}
            - --upstream=http://127.0.0.1:{{ $servicePort }}/
            - --proxy-endpoints-port={{ .Values.kubeRBACProxy.proxyEndpointsPort }}
            - --config-file=/etc/kube-rbac-proxy-config/config-file.yaml
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - --tls-cert-file=/tls/private/{{ .Values.tlsSecret.certItem }}
            - --tls-private-key-file=/tls/private/{{ .Values.tlsSecret.keyItem }}
            {{- if and .Values.kubeRBACProxy.tls.tlsClientAuth .Values.tlsSecret.caItem }}
            - --client-ca-file=/tls/private/{{ .Values.tlsSecret.caItem }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: kube-rbac-proxy-config
              mountPath: /etc/kube-rbac-proxy-config
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - name: {{ tpl .Values.tlsSecret.volumeName . | quote }}
              mountPath: /tls/private
              readOnly: true
            {{- end }}
            {{- with .Values.kubeRBACProxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.kubeRBACProxy.image.pullPolicy }}
          {{- if .Values.kubeRBACProxy.image.sha }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}@sha256:{{ .Values.kubeRBACProxy.image.sha }}"
          {{- else }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port}}
              name: {{ .Values.kubeRBACProxy.portName }}
              {{- if .Values.kubeRBACProxy.enableHostPort }}
              hostPort: {{ .Values.service.port }}
              {{- end }}
            - containerPort: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              {{- if .Values.kubeRBACProxy.enableProxyEndpointsHostPort }}
              hostPort: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              {{- end }}
              name: "http-healthz"
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              path: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- if .Values.kubeRBACProxy.resources }}
          resources:
          {{- toYaml .Values.kubeRBACProxy.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationMessageParams.enabled }}
          {{- with .Values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          {{- with .Values.kubeRBACProxy.env }}
          env:
            {{- range $key, $value := $.Values.kubeRBACProxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.kubeRBACProxy.containerSecurityContext }}
          securityContext:
          {{ toYaml .Values.kubeRBACProxy.containerSecurityContext | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- if or .Values.imagePullSecrets .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "ceems-exporter.imagePullSecrets" (dict "Values" .Values.ceemsExporter "imagePullSecrets" .Values.imagePullSecrets) | indent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- if or (.Values.hostPID) (.Values.eBPFProfiling.enabled) }}
      hostPID: true
      {{- else }}
      hostPID: false
      {{- end }}
      hostIPC: {{ .Values.hostIPC }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        {{- if .Values.hostRootFsMount.enabled }}
        - name: root
          hostPath:
            path: /
        {{- end }}
        {{- range $_, $mount := .Values.extraHostVolumeMounts }}
        - name: {{ $mount.name }}
          hostPath:
            path: {{ $mount.hostPath }}
            {{- with $mount.type }}
            type: {{ . }}
            {{- end }}
        {{- end -}}
        {{- if eq .Values.collectors.ipmi.enabled true }}
        - name: ipmi
          hostPath:
            path: {{ .Values.collectors.ipmi.device }}
            type: CharDevice
        {{- end }}
        {{- if eq .Values.collectors.k8s.enabled true }}
        - name: pod-resources
          hostPath:
            path: {{ .Values.collectors.k8s.kubeletSocketDirectory }}
            type: Directory
        {{- end }}
        {{- if and (eq .Values.collectors.slurm.enabled true) (ne .Values.collectors.slurm.configDirectory "") }}
        - name: slurm-config
          hostPath:
            path: {{ .Values.collectors.slurm.configDirectory }}
            type: Directory
        {{- end }}
        {{- if eq .Values.collectors.libvirt.enabled true }}
        - name: persistent-qemu-xml-dir
          hostPath:
            path: /etc/libvirt/qemu
            type: Directory
        - name: runtime-qemu-xml-dir
          hostPath:
            path: /run/libvirt/qemu
            type: Directory
        {{- end }}
        {{- range $_, $mount := .Values.configmaps }}
        - name: {{ tpl $mount.name $ | quote }}
          configMap:
            name: {{ tpl $mount.name $ | quote }}
        {{- end }}
        {{- range $_, $mount := .Values.secrets }}
        - name: {{ tpl $mount.name $ | quote }}
          secret:
            secretName: {{tpl $mount.name $ | quote }}
        {{- end }}
        {{- if not (empty .Values.webConfig) }}
        - name: ceems-exporter-web-config
          secret:
            secretName: {{ template "ceems-exporter.fullname" . }}-web-config
        {{- end }}
        {{- if .Values.kubeRBACProxy.enabled }}
        - name: kube-rbac-proxy-config
          configMap:
            name: {{ template "ceems-exporter.fullname" . }}-rbac-config
        {{- end }}
        {{- if .Values.tlsSecret.enabled }}
        - name: {{ tpl .Values.tlsSecret.volumeName . | quote }}
          secret:
            secretName: {{ tpl .Values.tlsSecret.secretName . | quote }}
            items:
              - key: {{ required "Value tlsSecret.certItem must be set." .Values.tlsSecret.certItem | quote }}
                path: {{ .Values.tlsSecret.certItem | quote }}
              - key: {{ required "Value tlsSecret.keyItem must be set." .Values.tlsSecret.keyItem | quote }}
                path: {{ .Values.tlsSecret.keyItem | quote }}
              {{- if .Values.tlsSecret.caItem }}
              - key: {{ .Values.tlsSecret.caItem | quote }}
                path: {{ .Values.tlsSecret.caItem | quote }}
              {{- end }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.collectors.redfish.enabled }}
        - name: redfish-config
          secret:
            secretName: {{ template "ceems-exporter.fullname" . }}-redfish-config
        {{- end }}
        {{- if .Values.eBPFProfiling.enabled }}
        - name: profiling-config
          secret:
            secretName: {{ template "ceems-exporter.fullname" . }}-profiling-config
        {{- end }}
