{{- if .Values.collectors.emissions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ceems-exporter.fullname" . }}-emissions
  namespace: {{ include "ceems-exporter.namespace" . }}
  labels:
    {{- include "ceems-exporter.labels" . | nindent 4 }}
  {{- with .Values.collectors.emissions.deploy.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ceems-exporter.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ceems-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ ternary true false (or .Values.serviceAccount.automountServiceAccountToken .Values.kubeRBACProxy.enabled) }}
      {{- with .Values.priorityClassName }}
      securityContext:
        runAsNonRoot: true
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "ceems-exporter.serviceAccountName" . }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        {{- $servicePort := ternary .Values.kubeRBACProxy.port .Values.service.port .Values.kubeRBACProxy.enabled }}
        - name: ceems-exporter
          image: {{ include "ceems-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/ceems_exporter
          args:
            - --web.listen-address=[$(HOST_IP)]:{{ $servicePort }}
            - --collector.disable-defaults
            - --collector.emissions
            {{- range $_, $value := .Values.collectors.emissions.providers }}
            - --collector.emissions.provider={{ $value }}
            {{- end }}
            {{- if not (empty .Values.webConfig) }}
            - --web.config.file=/etc/ceems-web/config.yaml
            {{- end }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              {{- if .Values.kubeRBACProxy.enabled }}
              value: 127.0.0.1
              {{- else if .Values.service.listenOnAllInterfaces }}
              value: 0.0.0.0
              {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
              {{- end }}
            {{- range $key, $value := .Values.collectors.emissions.deploy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if eq .Values.kubeRBACProxy.enabled false }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_exporter
                - -p
                - {{ $servicePort | quote }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            exec:
              command:
                - /bin/liveness-probe.sh
                - -a
                - ceems_exporter
                - -p
                - {{ $servicePort | quote }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationMessageParams.enabled }}
          {{- with .Values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if not (empty .Values.webConfig) }}
            - name: ceems-exporter-web-config
              mountPath: /etc/ceems-web
            {{- end }}
        {{-  if .Values.kubeRBACProxy.enabled  }}
        - name: kube-rbac-proxy
          args:
            {{- range $_, $arg := .Values.kubeRBACProxy.additionalArgs }}
            {{- if (hasKey $arg "value") }}
            - --{{ $arg.name }}={{ $arg.value }}
            {{- else }}
            - --{{ $arg.name }}
            {{- end }}
            {{- end }}
            - --secure-listen-address=:{{ .Values.service.port}}
            - --upstream=http://127.0.0.1:{{ $servicePort }}/
            - --proxy-endpoints-port={{ .Values.kubeRBACProxy.proxyEndpointsPort }}
            - --config-file=/etc/kube-rbac-proxy-config/config-file.yaml
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - --tls-cert-file=/tls/private/{{ .Values.tlsSecret.certItem }}
            - --tls-private-key-file=/tls/private/{{ .Values.tlsSecret.keyItem }}
            {{- if and .Values.kubeRBACProxy.tls.tlsClientAuth .Values.tlsSecret.caItem }}
            - --client-ca-file=/tls/private/{{ .Values.tlsSecret.caItem }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: kube-rbac-proxy-config
              mountPath: /etc/kube-rbac-proxy-config
            {{- if and .Values.kubeRBACProxy.tls.enabled .Values.tlsSecret.enabled }}
            - name: {{ tpl .Values.tlsSecret.volumeName . | quote }}
              mountPath: /tls/private
              readOnly: true
            {{- end }}
            {{- with .Values.kubeRBACProxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.kubeRBACProxy.image.pullPolicy }}
          {{- if .Values.kubeRBACProxy.image.sha }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}@sha256:{{ .Values.kubeRBACProxy.image.sha }}"
          {{- else }}
          image: "{{ .Values.imageRegistry | default .Values.kubeRBACProxy.image.registry}}/{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port}}
              name: {{ .Values.kubeRBACProxy.portName }}
              {{- if .Values.kubeRBACProxy.enableHostPort }}
              hostPort: {{ .Values.service.port }}
              {{- end }}
            - containerPort: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              {{- if .Values.kubeRBACProxy.enableProxyEndpointsHostPort }}
              hostPort: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              {{- end }}
              name: "http-healthz"
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ .Values.kubeRBACProxy.proxyEndpointsPort }}
              path: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- if .Values.kubeRBACProxy.resources }}
          resources:
          {{- toYaml .Values.kubeRBACProxy.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.terminationMessageParams.enabled }}
          {{- with .Values.terminationMessageParams }}
          terminationMessagePath: {{ .terminationMessagePath }}
          terminationMessagePolicy: {{ .terminationMessagePolicy }}
          {{- end }}
          {{- end }}
          {{- with .Values.kubeRBACProxy.env }}
          env:
            {{- range $key, $value := $.Values.kubeRBACProxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.kubeRBACProxy.containerSecurityContext }}
          securityContext:
          {{ toYaml .Values.kubeRBACProxy.containerSecurityContext | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if or .Values.imagePullSecrets .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "ceems-exporter.imagePullSecrets" (dict "Values" .Values.ceemsExporter "imagePullSecrets" .Values.imagePullSecrets) | indent 8 }}
      {{- end }}
      {{- with .Values.collectors.emissions.deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if not (empty .Values.webConfig) }}
        - name: ceems-exporter-web-config
          secret:
            secretName: {{ template "ceems-exporter.fullname" . }}-web-config
        {{- end }}
        {{- if .Values.kubeRBACProxy.enabled }}
        - name: kube-rbac-proxy-config
          configMap:
            name: {{ template "ceems-exporter.fullname" . }}-rbac-config
        {{- end }}
        {{- if .Values.tlsSecret.enabled }}
        - name: {{ tpl .Values.tlsSecret.volumeName . | quote }}
          secret:
            secretName: {{ tpl .Values.tlsSecret.secretName . | quote }}
            items:
              - key: {{ required "Value tlsSecret.certItem must be set." .Values.tlsSecret.certItem | quote }}
                path: {{ .Values.tlsSecret.certItem | quote }}
              - key: {{ required "Value tlsSecret.keyItem must be set." .Values.tlsSecret.keyItem | quote }}
                path: {{ .Values.tlsSecret.keyItem | quote }}
              {{- if .Values.tlsSecret.caItem }}
              - key: {{ .Values.tlsSecret.caItem | quote }}
                path: {{ .Values.tlsSecret.caItem | quote }}
              {{- end }}
        {{- end }}
{{- end }}
