{{- if .Values.eBPFProfiling.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ceems-exporter.fullname" . }}-profiling-config
  namespace: {{ include "ceems-exporter.namespace" . }}
type: Opaque
data:
  config.yaml: {{ include "ceems-exporter.profiling-config" . | b64enc }}
{{- end }}
