{{- if .Values.kubeRBACProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ceems-exporter.fullname" . }}-rbac-config
  namespace: {{ include "ceems-exporter.namespace" . }}
data:
  config-file.yaml: |+
    authorization:
      resourceAttributes:
        namespace: {{ template "ceems-exporter.namespace" . }}
        apiVersion: v1
        resource: services
        subresource: {{ template "ceems-exporter.fullname" . }}
        name: {{ template "ceems-exporter.fullname" . }}
{{- end }}
