{{- if .Values.collectors.redfish.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ceems-exporter.fullname" . }}-redfish-config
  namespace: {{ include "ceems-exporter.namespace" . }}
type: Opaque
data:
  config.yaml: {{ include "ceems-exporter.redfish-config" . | b64enc }}
{{- end }}
