{{- if .Values.prometheus.monitor.enabled }}
---
apiVersion: {{ .Values.prometheus.monitor.apiVersion | default "monitoring.coreos.com/v1" }}
kind: ServiceMonitor
metadata:
  name: {{ include "ceems-exporter.fullname" . }}
  namespace: {{ include "ceems-exporter.monitor-namespace" . }}
  labels:
    {{- include "ceems-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheus.monitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" .Values.prometheus.monitor.jobLabel }}
  {{- include "servicemonitor.scrapeLimits" .Values.prometheus.monitor | nindent 2 }}
  {{- with .Values.prometheus.monitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.prometheus.monitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
    {{- with .Values.prometheus.monitor.selectorOverride }}
      {{- toYaml . | nindent 6 }}
    {{- else }}
      {{- include "ceems-exporter.selectorLabels" . | nindent 6 }}
    {{- end }}
  {{- with .Values.prometheus.monitor.attachMetadata }}
  attachMetadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
    - port: {{ .Values.service.portName }}
      {{- include "servicemonitor.authConfig" . | nindent 6 }}
      {{- with .Values.prometheus.monitor.proxyUrl }}
      proxyUrl: {{ . }}
      {{- end }}
      {{- with .Values.prometheus.monitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.prometheus.monitor.honorTimestamps }}
      honorTimestamps: {{ . }}
      {{- end }}
      {{- with .Values.prometheus.monitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.prometheus.monitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.monitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableHttp2: {{ default false .Values.prometheus.monitor.enableHttp2 }}
      filterRunning: {{ default true .Values.prometheus.monitor.filterRunning }}
      followRedirects: {{ default false .Values.prometheus.monitor.followRedirects }}
      {{- with .Values.prometheus.monitor.params }}
      params:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.prometheus.monitor.dcgmExporterEnabled }}
---
apiVersion: {{ .Values.prometheus.monitor.apiVersion | default "monitoring.coreos.com/v1" }}
kind: ServiceMonitor
metadata:
  name: {{ include "ceems-exporter.fullname" . }}-nvidia-dcgm-exporter
  namespace: {{ include "ceems-exporter.monitor-namespace" . }}
  labels:
    {{- include "ceems-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheus.monitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: gpu-metrics
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  namespaceSelector:
    any: true
{{- end }}
{{- if .Values.prometheus.monitor.amdDeviceMetricsExporterEnabled }}
---
apiVersion: {{ .Values.prometheus.monitor.apiVersion | default "monitoring.coreos.com/v1" }}
kind: ServiceMonitor
metadata:
  name: {{ include "ceems-exporter.fullname" . }}-amd-device-metrics-exporter
  namespace: {{ include "ceems-exporter.monitor-namespace" . }}
  labels:
    {{- include "ceems-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheus.monitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: exporter-port
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/service: default-metrics-exporter
  namespaceSelector:
    any: true
{{- end }}
{{- end }}
