{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceems-exporter.serviceAccountName" . }}
  namespace: {{ include "ceems-exporter.namespace" . }}
  labels: 
    {{- include "ceems-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if or .Values.serviceAccount.imagePullSecrets .Values.imagePullSecrets }}
imagePullSecrets:
  {{- include "kube-ceems.imagePullSecrets" (dict "Values" .Values.ceemsExporter "imagePullSecrets" .Values.serviceAccount.imagePullSecrets) | indent 2 }}
{{- end }}
{{- end -}}
