{{- if (not (empty .Values.webConfig)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ceems-exporter.fullname" . }}-web-config
  namespace: {{ include "ceems-exporter.namespace" . }}
stringData:
  config.yaml: |-
  {{- with .Values.webConfig }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
