name: CI
permissions: {}

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    # name: Lint and Test Charts
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          # renovate: github=helm/helm
          version: v4.0.0

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: '3.13'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          # renovate: github=helm/chart-testing
          version: v3.14.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed --config .github/linters/ct.yaml)"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_list=\"${changed//$'\n'/ }\"" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install test prerequisites
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          # Install PV provider
          kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml

          # Install nginx ingress controller
          helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
          kubectl get service --namespace ingress-nginx ingress-nginx-controller

          # Setup redfish emulator
          wget https://github.com/ceems-dev/fake-energy-counters/releases/download/v0.2.0/fake_energy_counters
          chmod +x fake_energy_counters
          # Start redfish emulator
          ./fake_energy_counters --counters.redfish &
          sleep 10

          # Setup runner IP in ci values file
          RUNNER_IP=$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
          sed -i "s/RUNNER_IP/${RUNNER_IP}/g" charts/kube-ceems/ci/09-with-redfish-proxy-values.yaml

      - name: Apply Gateway API CRDs
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl apply -k https://github.com/kubernetes-sigs/gateway-api/config/crd

      - name: Apply Prometheus Operator CRDs
        if: steps.list-changed.outputs.changed == 'true'
        run: helm install prometheus-operator-crds oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds

      - name: Run chart-testing (install)
        run: ct install --config .github/linters/ct.yaml

  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 # v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          MULTI_STATUS: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          # VALIDATE_CHECKOV: true - always scans everything and all charts have too much errors
          VALIDATE_EDITORCONFIG: true
          VALIDATE_ENV: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_PYTHON: true
          VALIDATE_RENOVATE: true # does not support newest renovate config
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_XML: true

  renovate-auto-merge:
    name: Auto-approve PRs from Renovate
    runs-on: ubuntu-24.04
    needs:
      - lint-test
      - super-linter
    if: >-
      github.event.pull_request.head.repo.full_name == github.repository 
      && contains(github.event.pull_request.labels.*.name, 'dependencies/auto-merge') 
      && (github.actor == 'renovate[bot]' || github.actor == 'ceems-helm-charts-renovate-helper[bot]')
    steps:
      # Using a GitHub App token, because GitHub Actions doesn't run on commits from github-actions bot
      # Used App:
      # https://github.com/organizations/prometheus-community/settings/apps/helm-charts-renovate-helper.
      # Ref: https://github.com/prometheus-community/helm-charts/issues/5213.
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: 1940518
          private-key: ${{ secrets.APP_RENOVATE_HELPER_PRIVATE_KEY }}

      - name: Approve PR
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --repo "${{ github.repository }}"
          gh pr merge ${{ github.event.pull_request.number }} --admin --squash --repo "${{ github.repository }}" --match-head-commit "${{ github.event.pull_request.head.sha }}" --delete-branch
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
